name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   name: Build Docker Image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Node.js Set Up
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 16

  #     - name: Downloading Node.js Package
  #       run: npm init -y

  #     - name: Docker Hub Login
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Docker Image Build
  #       run: |
  #         docker build -t josephmichael1/my-node-app:latest .

  #     - name: Push Docker Image
  #       run: docker push josephmichael1/my-node-app:latest

  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Minikube Installation
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: kubectl Installation
        run: |
          curl -LO "https://dl.k8s.io/release/v1.26.3/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Kubernetes Orchestration
        run: |
          pwd
          ls -al
          echo "the folder beneath it"
          ls -al ../
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl scale deployment my-node-app --replicas=6
          sleep 80
          # kubectl get pods
